import React, { useState } from 'react';
import { Brain, ChevronDown, ChevronUp } from 'lucide-react';

interface AIInterpretationProps {
    simple: string;
    advanced: string;
}

const AIInterpretation: React.FC<AIInterpretationProps> = ({ simple, advanced }) => {
    const [mode, setMode] = useState<'simple' | 'advanced'>('simple');
    const [isExpanded, setIsExpanded] = useState(true);

    return (
        <div className="bg-gradient-to-br from-indigo-50 to-purple-50 dark:from-indigo-950/30 dark:to-purple-950/30 rounded-xl p-6 border border-indigo-200 dark:border-indigo-800 shadow-lg">
            {/* Header */}
            <div className="flex items-center justify-between mb-4">
                <div className="flex items-center gap-3">
                    <div className="p-2 bg-indigo-600 rounded-lg">
                        <Brain className="w-6 h-6 text-white" />
                    </div>
                    <div>
                        <h3 className="text-lg font-bold text-slate-900 dark:text-white">
                            AI Interpretation of This Phase
                        </h3>
                        <p className="text-xs text-indigo-600 dark:text-indigo-400 font-medium">
                            Powered by AI Analysis
                        </p>
                    </div>
                </div>
                <button
                    onClick={() => setIsExpanded(!isExpanded)}
                    className="p-2 hover:bg-indigo-100 dark:hover:bg-indigo-900/50 rounded-lg transition-colors"
                >
                    {isExpanded ? (
                        <ChevronUp className="w-5 h-5 text-slate-600 dark:text-slate-400" />
                    ) : (
                        <ChevronDown className="w-5 h-5 text-slate-600 dark:text-slate-400" />
                    )}
                </button>
            </div>

            {isExpanded && (
                <>
                    {/* Mode Toggle */}
                    <div className="flex gap-2 mb-4">
                        <button
                            onClick={() => setMode('simple')}
                            className={`px-4 py-2 rounded-lg text-sm font-medium transition-all ${mode === 'simple'
                                    ? 'bg-indigo-600 text-white shadow-md'
                                    : 'bg-white dark:bg-slate-800 text-slate-600 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-700'
                                }`}
                        >
                            Simple
                        </button>
                        <button
                            onClick={() => setMode('advanced')}
                            className={`px-4 py-2 rounded-lg text-sm font-medium transition-all ${mode === 'advanced'
                                    ? 'bg-indigo-600 text-white shadow-md'
                                    : 'bg-white dark:bg-slate-800 text-slate-600 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-700'
                                }`}
                        >
                            Why This Happens
                        </button>
                    </div>

                    {/* Content */}
                    <div className="bg-white dark:bg-slate-800 rounded-lg p-4 border border-indigo-200 dark:border-indigo-800">
                        <p className="text-slate-700 dark:text-slate-300 leading-relaxed text-sm">
                            {mode === 'simple' ? simple : advanced}
                        </p>
                    </div>

                    {/* Disclaimer */}
                    <div className="mt-3 p-3 bg-indigo-100 dark:bg-indigo-900/30 rounded-lg border border-indigo-200 dark:border-indigo-800">
                        <p className="text-xs text-indigo-900 dark:text-indigo-300">
                            <strong>Note:</strong> This interpretation is generated by AI based on your life trend data. It provides guidance, not absolute predictions.
                        </p>
                    </div>
                </>
            )}
        </div>
    );
};

export default AIInterpretation;
