import logging
import json
from typing import List, Dict, Any, Optional
from astro_app.backend.services.gemini_service import GeminiService

logger = logging.getLogger(__name__)

class TransitAIService:
    def __init__(self):
        self.gemini_service = GeminiService()

    def get_system_prompt(self, context: str) -> str:
        """
        Returns the appropriate system prompt based on context.
        """
        base_prompt = """You are VedaAI, an expert astrological interpreter. 
CRITICAL RULE: NEVER calculate planetary positions, dates, or transits. 
You are provided with DETERMINISTIC DATA from an astronomy engine. Your job is ONLY to interpret this data for the user.
Do not hallucinate new transits. Do not change the dates.
Focus on BEHAVIORAL GUIDANCE, PSYCHOLOGICAL INSIGHT, and STRATEGIC TIMING.
Use a calm, grounded, empowering tone. Avoid fear-mongering and fatalism."""

        if context == "daily_summary":
            return base_prompt + "\n\nTask: specific daily summary. Focus on the 'Theme of the Day'."
        elif context == "explanation":
             return base_prompt + "\n\nTask: deep dive explanation of a specific transit."
        elif context == "timeline":
            return base_prompt + "\n\nTask: narrative storytelling of the upcoming month."
        
        return base_prompt

    def generate_daily_summary(self, chart_data: Dict[str, Any], transits: List[Dict[str, Any]]) -> Dict[str, Any]:
        """
        Generates daily summary, priority ranking, and action guidance.
        """
        system_prompt = self.get_system_prompt("daily_summary")
        
        user_prompt = f"""
        Analyze these active transits for today:
        {json.dumps(transits, indent=2)}
        
        User Ascendant: {chart_data.get('ascendant', {}).get('sign', 'Unknown')}
        User Moon Sign: {chart_data.get('moon_sign', 'Unknown')}

        Provide a JSON response with:
        1. "summary": A 2-sentence grounded summary of the day's energy.
        2. "priority_order": A list of the IDs of the top 3 most important transits to focus on (from the input list).
        3. "action_guidance": {{
            "do": ["Action 1", "Action 2", "Action 3"],
            "avoid": ["Avoid 1", "Avoid 2", "Action 3"]
        }}
        """

        try:
            # We enforce JSON output structure via prompt engineering (Gemini usually complies well)
            response_text = self.gemini_service.generate_chat_response(
                user_query=user_prompt,
                system_prompt=system_prompt + "\n\nOUTPUT MUST BE VALID JSON ONLY."
            )
            
            # Clean formatting if markdown is included
            cleaned_text = response_text.replace("```json", "").replace("```", "").strip()
            return json.loads(cleaned_text)
        except Exception as e:
            logger.error(f"Error generating daily summary: {e}")
            return {
                "summary": "Today offers a mix of energies. Focus on maintaining balance and sticking to your routine.",
                "priority_order": [],
                "action_guidance": {
                    "do": ["Stay calm", "Focus on work", "Rest well"],
                    "avoid": ["Impulsive decisions", "Arguments", "Over-exertion"]
                }
            }

    def explain_transit(self, transit_event: Dict[str, Any], mode: str = "Beginner") -> Dict[str, Any]:
        """
        Explains a specific transit in a specific mode.
        """
        system_prompt = self.get_system_prompt("explanation")
        
        mode_instructions = {
            "Beginner": "Simple, accessible language. Avoid jargon.",
            "Practitioner": "Use technical terms (aspects, dashas). Go deep.",
            "Therapeutic": "Focus on emotional growth and healing.",
            "Strategic": "Focus on business, career, and decision timing."
        }
        
        instruction = mode_instructions.get(mode, mode_instructions["Beginner"])

        user_prompt = f"""
        Explain this transit event:
        {json.dumps(transit_event, indent=2)}

        Mode: {mode}
        Instruction: {instruction}

        Provide a JSON response with:
        1. "explanation": A 2-paragraph explanation.
        2. "why_this_matters": A 1-sentence punchy tagline explaining the core impact.
        3. "strength_rating": (Autogenerated, just confirm generic strength 1-10 based on planet nature)
        """

        try:
            response_text = self.gemini_service.generate_chat_response(
                user_query=user_prompt,
                system_prompt=system_prompt + "\n\nOUTPUT MUST BE VALID JSON ONLY."
            )
            
            cleaned_text = response_text.replace("```json", "").replace("```", "").strip()
            return json.loads(cleaned_text)
        except Exception as e:
            logger.error(f"Error explaining transit: {e}")
            return {
                "explanation": "This transit brings specific energy to your life. Observe how it affects your routine.",
                "why_this_matters": "It marks a time of change.",
                "strength_rating": 5
            }

    def get_timeline_story(self, timeline_events: List[Dict[str, Any]]) -> str:
        """
        Generates a narrative story for the next 30 days.
        """
        system_prompt = self.get_system_prompt("timeline")
        
        user_prompt = f"""
        Create a narrative story for the next 30 days based on these events:
        {json.dumps(timeline_events, indent=2)}

        Write it as a cohesive paragraph (max 3 sentences).
        Start with "The next month begins with..."
        """

        try:
            response_text = self.gemini_service.generate_chat_response(
                user_query=user_prompt,
                system_prompt=system_prompt
            )
            return response_text.strip()
        except Exception as e:
            logger.error(f"Error generating timeline story: {e}")
            return "The coming month brings a series of planetary shifts. Navigate them with awareness and patience."
