
"""
Rich metadata for the 27 Nakshatras.
"""

NAKSHATRA_METADATA = {
    "Ashwini": {
        "id": 1,
        "lord": "Ketu",
        "symbol": "Horse's Head",
        "deity": "Ashwini Kumaras (Physicians of Gods)",
        "gana": "Deva",
        "yoni": "Horse",
        "nadi": "Adi (Vata)",
        "element": "Earth",
        "direction": "South",
        "quality": "Light/Swift",
        "sex": "Male",
        "lucky_letters": "Chu, Che, Cho, La"
    },
    "Bharani": {
        "id": 2,
        "lord": "Venus",
        "symbol": "Yoni (Female reproductive organ)",
        "deity": "Yama (God of Death)",
        "gana": "Manushya",
        "yoni": "Elephant",
        "nadi": "Madhya (Pitta)",
        "element": "Earth",
        "direction": "West",
        "quality": "Fierce/Severe",
        "sex": "Female",
        "lucky_letters": "Li, Lu, Le, Lo"
    },
    "Krittika": {
        "id": 3,
        "lord": "Sun",
        "symbol": "Knife or Razor",
        "deity": "Agni (God of Fire)",
        "gana": "Rakshasa",
        "yoni": "Sheep",
        "nadi": "Antya (Kapha)",
        "element": "Fire",
        "direction": "North",
        "quality": "Mixed",
        "sex": "Female",
        "lucky_letters": "A, I, U, E"
    },
    "Rohini": {
        "id": 4,
        "lord": "Moon",
        "symbol": "Chariot or Cart",
        "deity": "Brahma (Creator)",
        "gana": "Manushya",
        "yoni": "Serpent",
        "nadi": "Antya (Kapha)",
        "element": "Earth",
        "direction": "East",
        "quality": "Fixed/Steady",
        "sex": "Female",
        "lucky_letters": "O, Va, Vi, Vu"
    },
    "Mrigashira": {
        "id": 5,
        "lord": "Mars",
        "symbol": "Deer's Head",
        "deity": "Soma (Moon God)",
        "gana": "Deva",
        "yoni": "Serpent",
        "nadi": "Madhya (Pitta)",
        "element": "Air",
        "direction": "South",
        "quality": "Soft/Mild",
        "sex": "Neuter",
        "lucky_letters": "We, Wo, Ka, Ki"
    },
    "Ardra": {
        "id": 6,
        "lord": "Rahu",
        "symbol": "Teardrop or Diamond",
        "deity": "Rudra (Storm God)",
        "gana": "Manushya",
        "yoni": "Dog",
        "nadi": "Adi (Vata)",
        "element": "Water",
        "direction": "West",
        "quality": "Sharp/Dreadful",
        "sex": "Female",
        "lucky_letters": "Ku, Gha, Ng, Chha"
    },
    "Punarvasu": {
        "id": 7,
        "lord": "Jupiter",
        "symbol": "Bow and Quiver",
        "deity": "Aditi (Mother of Gods)",
        "gana": "Deva",
        "yoni": "Cat",
        "nadi": "Adi (Vata)",
        "element": "Water",
        "direction": "North",
        "quality": "Movable",
        "sex": "Male",
        "lucky_letters": "Ke, Ko, Ha, Hi"
    },
    "Pushya": {
        "id": 8,
        "lord": "Saturn",
        "symbol": "Cow's Udder or Lotus",
        "deity": "Brihaspati (Guru of Gods)",
        "gana": "Deva",
        "yoni": "Goat",
        "nadi": "Madhya (Pitta)",
        "element": "Water",
        "direction": "East",
        "quality": "Light/Swift",
        "sex": "Male",
        "lucky_letters": "Hu, He, Ho, Da"
    },
    "Ashlesha": {
        "id": 9,
        "lord": "Mercury",
        "symbol": "Coiled Serpent",
        "deity": "Nagas (Serpent Deities)",
        "gana": "Rakshasa",
        "yoni": "Cat",
        "nadi": "Antya (Kapha)",
        "element": "Water",
        "direction": "South",
        "quality": "Sharp/Dreadful",
        "sex": "Female",
        "lucky_letters": "Di, Du, De, Do"
    },
    "Magha": {
        "id": 10,
        "lord": "Ketu",
        "symbol": "Royal Throne",
        "deity": "Pitris (Ancestors)",
        "gana": "Rakshasa",
        "yoni": "Rat",
        "nadi": "Antya (Kapha)",
        "element": "Water",
        "direction": "West",
        "quality": "Fierce/Severe",
        "sex": "Female",
        "lucky_letters": "Ma, Mi, Mu, Me"
    },
    "Purva Phalguni": {
        "id": 11,
        "lord": "Venus",
        "symbol": "Front Legs of a Bed",
        "deity": "Bhaga (God of Fortune)",
        "gana": "Manushya",
        "yoni": "Rat",
        "nadi": "Madhya (Pitta)",
        "element": "Fire",
        "direction": "North",
        "quality": "Fierce/Severe",
        "sex": "Female",
        "lucky_letters": "Mo, Ta, Ti, Tu"
    },
    "Uttara Phalguni": {
        "id": 12,
        "lord": "Sun",
        "symbol": "Back Legs of a Bed",
        "deity": "Aryaman (God of Contracts)",
        "gana": "Manushya",
        "yoni": "Cow",
        "nadi": "Adi (Vata)",
        "element": "Fire",
        "direction": "East",
        "quality": "Fixed/Steady",
        "sex": "Female",
        "lucky_letters": "Te, To, Pa, Pi"
    },
    "Hasta": {
        "id": 13,
        "lord": "Moon",
        "symbol": "Hand or Fist",
        "deity": "Savitr (Sun God)",
        "gana": "Deva",
        "yoni": "Buffalo",
        "nadi": "Adi (Vata)",
        "element": "Fire",
        "direction": "South",
        "quality": "Light/Swift",
        "sex": "Male",
        "lucky_letters": "Pu, Sha, Na, Tha"
    },
    "Chitra": {
        "id": 14,
        "lord": "Mars",
        "symbol": "Pearl or Gem",
        "deity": "Vishvakarma (Celestial Architect)",
        "gana": "Rakshasa",
        "yoni": "Tiger",
        "nadi": "Madhya (Pitta)",
        "element": "Fire",
        "direction": "West",
        "quality": "Soft/Mild",
        "sex": "Female",
        "lucky_letters": "Pe, Po, Ra, Ri"
    },
    "Swati": {
        "id": 15,
        "lord": "Rahu",
        "symbol": "Shoot of Plant or Coral",
        "deity": "Vayu (Wind God)",
        "gana": "Deva",
        "yoni": "Buffalo",
        "nadi": "Antya (Kapha)",
        "element": "Fire",
        "direction": "North",
        "quality": "Movable",
        "sex": "Female",
        "lucky_letters": "Ru, Re, Ro, Ta"
    },
    "Vishakha": {
        "id": 16,
        "lord": "Jupiter",
        "symbol": "Triumphal Arch",
        "deity": "Indra and Agni",
        "gana": "Rakshasa",
        "yoni": "Tiger",
        "nadi": "Antya (Kapha)",
        "element": "Fire",
        "direction": "East",
        "quality": "Mixed",
        "sex": "Female",
        "lucky_letters": "Ti, Tu, Te, To"
    },
    "Anuradha": {
        "id": 17,
        "lord": "Saturn",
        "symbol": "Lotus or Staff",
        "deity": "Mitra (God of Friendship)",
        "gana": "Deva",
        "yoni": "Deer",
        "nadi": "Madhya (Pitta)",
        "element": "Fire",
        "direction": "South",
        "quality": "Soft/Mild",
        "sex": "Male",
        "lucky_letters": "Na, Ni, Nu, Ne"
    },
    "Jyeshtha": {
        "id": 18,
        "lord": "Mercury",
        "symbol": "Earring or Umbrella",
        "deity": "Indra (King of Gods)",
        "gana": "Rakshasa",
        "yoni": "Deer",
        "nadi": "Adi (Vata)",
        "element": "Air",
        "direction": "West",
        "quality": "Sharp/Dreadful",
        "sex": "Female",
        "lucky_letters": "No, Ya, Yi, Yu"
    },
    "Mula": {
        "id": 19,
        "lord": "Ketu",
        "symbol": "Bunch of Roots",
        "deity": "Nirriti (Goddess of Destruction)",
        "gana": "Rakshasa",
        "yoni": "Dog",
        "nadi": "Adi (Vata)",
        "element": "Air",
        "direction": "North",
        "quality": "Sharp/Dreadful",
        "sex": "Neuter",
        "lucky_letters": "Ye, Yo, Ba, Bi"
    },
    "Purva Ashadha": {
        "id": 20,
        "lord": "Venus",
        "symbol": "Elephant Tusk or Fan",
        "deity": "Apah (Water Goddess)",
        "gana": "Manushya",
        "yoni": "Monkey",
        "nadi": "Madhya (Pitta)",
        "element": "Air",
        "direction": "East",
        "quality": "Fierce/Severe",
        "sex": "Female",
        "lucky_letters": "Bu, Dha, Bha, Dha"
    },
    "Uttara Ashadha": {
        "id": 21,
        "lord": "Sun",
        "symbol": "Elephant Tusk or Bed",
        "deity": "Vishwadevas (Universal Gods)",
        "gana": "Manushya",
        "yoni": "Mongoose",
        "nadi": "Antya (Kapha)",
        "element": "Air",
        "direction": "South",
        "quality": "Fixed/Steady",
        "sex": "Female",
        "lucky_letters": "Bhe, Bho, Ja, Ji"
    },
    "Shravana": {
        "id": 22,
        "lord": "Moon",
        "symbol": "Ear or Three Footprints",
        "deity": "Vishnu (Preserver)",
        "gana": "Deva",
        "yoni": "Monkey",
        "nadi": "Antya (Kapha)",
        "element": "Air",
        "direction": "North",
        "quality": "Movable",
        "sex": "Male",
        "lucky_letters": "Ju, Je, Jo, Gha"
    },
    "Dhanishta": {
        "id": 23,
        "lord": "Mars",
        "symbol": "Drum or Flute",
        "deity": "The Vasus (Elemental Gods)",
        "gana": "Rakshasa",
        "yoni": "Lion",
        "nadi": "Madhya (Pitta)",
        "element": "Ether",
        "direction": "West",
        "quality": "Movable",
        "sex": "Female",
        "lucky_letters": "Ga, Gi, Gu, Ge"
    },
    "Shatabhisha": {
        "id": 24,
        "lord": "Rahu",
        "symbol": "Empty Circle or 100 Physicians",
        "deity": "Varuna (God of Cosmic Waters)",
        "gana": "Rakshasa",
        "yoni": "Horse",
        "nadi": "Adi (Vata)",
        "element": "Ether",
        "direction": "South",
        "quality": "Movable",
        "sex": "Neuter",
        "lucky_letters": "Go, Sa, Si, Su"
    },
    "Purva Bhadrapada": {
        "id": 25,
        "lord": "Jupiter",
        "symbol": "Sword or Two-faced Man",
        "deity": "Aja Ekapada (One-footed Goat)",
        "gana": "Manushya",
        "yoni": "Lion",
        "nadi": "Adi (Vata)",
        "element": "Ether",
        "direction": "West",
        "quality": "Fierce/Severe",
        "sex": "Male",
        "lucky_letters": "Se, So, Da, Di"
    },
    "Uttara Bhadrapada": {
        "id": 26,
        "lord": "Saturn",
        "symbol": "Twins or Back Legs of Bed",
        "deity": "Ahir Budhnya (Serpent of the Deep)",
        "gana": "Manushya",
        "yoni": "Cow",
        "nadi": "Madhya (Pitta)",
        "element": "Ether",
        "direction": "North",
        "quality": "Fixed/Steady",
        "sex": "Male",
        "lucky_letters": "Du, Tha, Jna, Da"
    },
    "Revati": {
        "id": 27,
        "lord": "Mercury",
        "symbol": "Drum or Fish",
        "deity": "Pushan (Protector of Flocks)",
        "gana": "Deva",
        "yoni": "Elephant",
        "nadi": "Antya (Kapha)",
        "element": "Ether",
        "direction": "East",
        "quality": "Soft/Mild",
        "sex": "Female",
        "lucky_letters": "De, Do, Cha, Chi"
    }
}
